version: "3.9"
services:
  booksapp:
    build: .
    ports:
      - "12321:3000"
    depends_on:
      - "db"
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
    platform: linux/x86_64
    volumes:
      - .db:/var/lib/mysql
