version: "3.9"
services:
  booksapp:
    build: .
    ports:
      - "12321:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
  db:
    image: mysql:8-oracle
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/mysql
    healthcheck:
      test: "mysqladmin ping -h 127.0.0.1 -P 3306"
      interval: 3s
      retries: 5
volumes:
  db-data:
